name: Deploy

on:
  push:
    branches:
      - master

jobs:
phpcs:
  name: Test
  runs-on: ubuntu-latest
  steps:
    - name: Get Latest Code
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: "12"

      - name: Check Code Standards
        run: |
          npm install
          npm run lint
