# name: Deploy

# on:
#   push:
#     branches:
#       - development

# jobs:
#   cd:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@master

#       - name: Deploy Using ssh
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST_PROD }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
#           port: ${{ secrets.SSH_PORT }}
#           script: |
#             cd /var/www/html/equinox_indo
#             chown -R $USER:www-data storage
#             chmod -R 775 storage
#             git pull origin development
#             composer install
